spring.application.name=api-gateway
server.port=8762

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# Discovery locator (auto-routes by service name, optional but handy)
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# CORS
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174,http://localhost:3000,http://127.0.0.1:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true

jwt.service=this_is_secret_key_of_quiz_application_1234

# Routes ? all using server.webflux prefix
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=question
spring.cloud.gateway.server.webflux.routes[1].uri=lb://QUESTION
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/question/**

spring.cloud.gateway.server.webflux.routes[2].id=quiz
spring.cloud.gateway.server.webflux.routes[2].uri=lb://QUIZ
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/quiz/**

spring.cloud.gateway.server.webflux.routes[3].id=profile-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://PROFILE-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/profile/**

spring.cloud.gateway.server.webflux.routes[4].id=result-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://RESULT-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/results/**

spring.http.codecs.max-in-memory-size=10MB