spring.application.name=profile-service

server.port=8070


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/profiledb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

cloudinary.cloud-name=dolfdzaf2
cloudinary.api-key=694238974681883
cloudinary.api-secret=O2_f93cNM72RGx1VO5vxNAYA1x4

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000